### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by jistr**

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
LGTM 🎉

**Comment by adithyaakrishna** [comment]
@jistr Instead of disabling the CI, how about if we add a workflow trigger that has to be done manually?

**Comment by jistr** [comment]
@adithyaakrishna It's now enabled automatically... Not sure why would we disable it or run it manually?

**Comment by adithyaakrishna** [comment]
Yes, I guess its not needed 😶

**Pull request merged**
